-- Catalog products and their stock levels (spec §13).
-- Constraints mirror the domain rules so a bug in application code fails loudly instead of corrupting data.

CREATE TABLE products (
    id            UUID          PRIMARY KEY,
    sku           TEXT          NOT NULL,
    name          TEXT          NOT NULL,
    price_amount  NUMERIC(19,4) NOT NULL,
    currency      CHAR(3)       NOT NULL,
    status        TEXT          NOT NULL,
    created_at    TIMESTAMPTZ   NOT NULL,
    updated_at    TIMESTAMPTZ   NOT NULL,
    CONSTRAINT products_sku_unique         UNIQUE (sku),
    CONSTRAINT products_sku_format         CHECK (sku ~ '^[A-Z0-9][A-Z0-9-]{2,63}$'),
    CONSTRAINT products_name_length        CHECK (char_length(btrim(name)) BETWEEN 1 AND 200),
    CONSTRAINT products_price_non_negative CHECK (price_amount >= 0),
    CONSTRAINT products_currency_format    CHECK (currency ~ '^[A-Z]{3}$'),
    CONSTRAINT products_status_valid       CHECK (status IN ('ACTIVE', 'INACTIVE')),
    CONSTRAINT products_timestamps_ordered CHECK (updated_at >= created_at)
);

COMMENT ON TABLE products IS 'Catalog products. id is a time-ordered UUIDv7 generated by the application (ADR-005).';

CREATE TABLE inventory (
    product_id          UUID        PRIMARY KEY REFERENCES products (id) ON DELETE RESTRICT,
    total_quantity      INT         NOT NULL,
    available_quantity  INT         NOT NULL,
    reserved_quantity   INT         NOT NULL,
    sold_quantity       INT         NOT NULL,
    version             BIGINT      NOT NULL DEFAULT 0,
    updated_at          TIMESTAMPTZ NOT NULL,
    CONSTRAINT inventory_total_non_negative     CHECK (total_quantity >= 0),
    CONSTRAINT inventory_available_non_negative CHECK (available_quantity >= 0),
    CONSTRAINT inventory_reserved_non_negative  CHECK (reserved_quantity >= 0),
    CONSTRAINT inventory_sold_non_negative      CHECK (sold_quantity >= 0),
    CONSTRAINT inventory_version_non_negative   CHECK (version >= 0),
    CONSTRAINT inventory_stock_conservation
        CHECK (available_quantity + reserved_quantity + sold_quantity = total_quantity)
);

COMMENT ON TABLE inventory IS
    'Stock level per product: the inventory source of truth. This is the contended row during a flash sale, '
    'so it deliberately has no secondary indexes.';
COMMENT ON CONSTRAINT inventory_stock_conservation ON inventory IS
    'Every unit is in exactly one bucket: available + reserved + sold = total.';
